version: '3.1'
networks:
  default:
    external:
      name: dev
services:
  mysql:
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql
  adminer:
    build: ./adminer
    restart: always
    links:
      - mysql
  redis:
    build: ./redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ${DATA_PATH}/redis:/data
  redis-adminer:
    build: ./redis-adminer
    restart: always
    environment:
      REDIS_1_HOST: redis
    links:
      - redis
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes: 
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${WEB_PATH}:/var/www
    links:
      - redis-adminer
      - adminer
      - php-fpm
  php-fpm:
    build: ./php-fpm
    volumes:
      - ${WEB_PATH}:/var/www/html:cached


